### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by IvanMc98** [SistemasTecTlaxiaco/infografia-IvanMc98#1]
[Infografia - Realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/infografia-IvanMc98/files/8054831/Infografia.-.Realidad.aumentada.pdf)

**Comment by lizzeth99** [comment]
calificacion: 20% 
cumple con todos los datos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
