### ISSUE TITLE
Ing. de requisitos (Infografía)

### ISSUE THREAD

**Issue by IvanMc98** [SistemasTecTlaxiaco/infografia-IvanMc98#2]
**Infografia**

![Infografia - Ivan montoya cruz](https://user-images.githubusercontent.com/72116117/111845082-caf83400-88c9-11eb-8197-5676d836299f.png)

**Comment by IvanMc98** [comment]
[Infografia-Ivan Montoya.pdf](https://github.com/SistemasTecTlaxiaco/infografia-IvanMc98/files/6174035/Infografia-Ivan.Montoya.pdf)

**Comment by dulce-blm** [comment]
La infografía cumple con todos los criterios. Calificación 20 puntos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
